/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminDashboardRouteImport } from './routes/admin-dashboard'
import { Route as AiChatRouteImport } from './routes/ai-chat'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FacultyDashboardRouteImport } from './routes/faculty-dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MarksRouteImport } from './routes/marks'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as StudentDashboardRouteImport } from './routes/student-dashboard'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin-dashboard',
  path: '/admin-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AiChatRoute = AiChatRouteImport.update({
  id: '/ai-chat',
  path: '/ai-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyDashboardRoute = FacultyDashboardRouteImport.update({
  id: '/faculty-dashboard',
  path: '/faculty-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MarksRoute = MarksRouteImport.update({
  id: '/marks',
  path: '/marks',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentDashboardRoute = StudentDashboardRouteImport.update({
  id: '/student-dashboard',
  path: '/student-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/ai-chat': typeof AiChatRoute
  '/analytics': typeof AnalyticsRoute
  '/attendance': typeof AttendanceRoute
  '/contact': typeof ContactRoute
  '/faculty-dashboard': typeof FacultyDashboardRoute
  '/login': typeof LoginRoute
  '/marks': typeof MarksRoute
  '/profile': typeof ProfileRoute
  '/student-dashboard': typeof StudentDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/ai-chat': typeof AiChatRoute
  '/analytics': typeof AnalyticsRoute
  '/attendance': typeof AttendanceRoute
  '/contact': typeof ContactRoute
  '/faculty-dashboard': typeof FacultyDashboardRoute
  '/login': typeof LoginRoute
  '/marks': typeof MarksRoute
  '/profile': typeof ProfileRoute
  '/student-dashboard': typeof StudentDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/ai-chat': typeof AiChatRoute
  '/analytics': typeof AnalyticsRoute
  '/attendance': typeof AttendanceRoute
  '/contact': typeof ContactRoute
  '/faculty-dashboard': typeof FacultyDashboardRoute
  '/login': typeof LoginRoute
  '/marks': typeof MarksRoute
  '/profile': typeof ProfileRoute
  '/student-dashboard': typeof StudentDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin-dashboard'
    | '/ai-chat'
    | '/analytics'
    | '/attendance'
    | '/contact'
    | '/faculty-dashboard'
    | '/login'
    | '/marks'
    | '/profile'
    | '/student-dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin-dashboard'
    | '/ai-chat'
    | '/analytics'
    | '/attendance'
    | '/contact'
    | '/faculty-dashboard'
    | '/login'
    | '/marks'
    | '/profile'
    | '/student-dashboard'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin-dashboard'
    | '/ai-chat'
    | '/analytics'
    | '/attendance'
    | '/contact'
    | '/faculty-dashboard'
    | '/login'
    | '/marks'
    | '/profile'
    | '/student-dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AiChatRoute: typeof AiChatRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AttendanceRoute: typeof AttendanceRoute
  ContactRoute: typeof ContactRoute
  FacultyDashboardRoute: typeof FacultyDashboardRoute
  LoginRoute: typeof LoginRoute
  MarksRoute: typeof MarksRoute
  ProfileRoute: typeof ProfileRoute
  StudentDashboardRoute: typeof StudentDashboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-dashboard': {
      id: '/admin-dashboard'
      path: '/admin-dashboard'
      fullPath: '/admin-dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-chat': {
      id: '/ai-chat'
      path: '/ai-chat'
      fullPath: '/ai-chat'
      preLoaderRoute: typeof AiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty-dashboard': {
      id: '/faculty-dashboard'
      path: '/faculty-dashboard'
      fullPath: '/faculty-dashboard'
      preLoaderRoute: typeof FacultyDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marks': {
      id: '/marks'
      path: '/marks'
      fullPath: '/marks'
      preLoaderRoute: typeof MarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-dashboard': {
      id: '/student-dashboard'
      path: '/student-dashboard'
      fullPath: '/student-dashboard'
      preLoaderRoute: typeof StudentDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AiChatRoute: AiChatRoute,
  AnalyticsRoute: AnalyticsRoute,
  AttendanceRoute: AttendanceRoute,
  ContactRoute: ContactRoute,
  FacultyDashboardRoute: FacultyDashboardRoute,
  LoginRoute: LoginRoute,
  MarksRoute: MarksRoute,
  ProfileRoute: ProfileRoute,
  StudentDashboardRoute: StudentDashboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
